### ISSUE TITLE
Obscure line

### ISSUE THREAD

**Issue by alejandro-colomar** [secobau/nginx#1]
https://github.com/secobau/nginx/blob/e3dcd58231d2291b112955628ba493e11a291d5c/Dockerfile#L29

You should either place a trailing slash to denote that `/etc/nginx/` is a directory, or explicitly write the name of the link.

`ln` is a bit ambiguous:

<pre><b>NAME</b>
       ln - make links between files

<b>SYNOPSIS</b>
       <b>ln</b> [<u style="text-decoration-style:single">OPTION</u>]... [<u style="text-decoration-style:single">-T</u>] <u style="text-decoration-style:single">TARGET</u> <u style="text-decoration-style:single">LINK_NAME</u>
       <b>ln</b> [<u style="text-decoration-style:single">OPTION</u>]... <u style="text-decoration-style:single">TARGET</u>
       <b>ln</b> [<u style="text-decoration-style:single">OPTION</u>]... <u style="text-decoration-style:single">TARGET</u>... <u style="text-decoration-style:single">DIRECTORY</u>
       <b>ln</b> [<u style="text-decoration-style:single">OPTION</u>]... <u style="text-decoration-style:single">-t</u> <u style="text-decoration-style:single">DIRECTORY</u> <u style="text-decoration-style:single">TARGET</u>...
</pre>

**Comment by scolomar** [comment]
Please check `man ln` and then you will understand that the last element `/etc/nginx` can only be a directory.

**Comment by alejandro-colomar** [comment]
That text I copied is from ``man ln``

The first syntax (``-T``) can not be differentiated from the third one at first glance.

**Comment by scolomar** [comment]
Indeed.

**Comment by scolomar** [comment]
`ln [OPTION]... TARGET... DIRECTORY`

**Comment by alejandro-colomar** [comment]
``ln [OPTION]... [-T] TARGET LINK_NAME``

``ln [OPTION]... TARGET... DIRECTORY``

**Comment by scolomar** [comment]
In this option `ln [OPTION]... [-T] TARGET LINK_NAME` LINK_NAME cannot be a path.

**Comment by alejandro-colomar** [comment]
> 
> 
> In this option `ln [OPTION]... [-T] TARGET LINK_NAME` LINK_NAME cannot be a path.

That is not documented in the man page.  Are you sure?

**Comment by scolomar** [comment]
Absolutely :-)
Man pages are obscure by nature but not impossible to understand.

**Comment by alejandro-colomar** [comment]
Maybe you can add a patch to https://github.com/mkerrisk/man-pages

**Comment by alejandro-colomar** [comment]
Maybe you can add a patch to the ``ln`` man page

**Comment by alejandro-colomar** [comment]
I did a test, and both forms (1 and 3) work with the same syntax, and work differently.

If ``/etc/nginx/`` didn't exist previously, the link will be created and it will be named ``nginx``.

``-T`` has to be used to be unambiguous.  (or a trailing slash)

**Comment by scolomar** [comment]
I would say that you need to prove that the following line can cause an unexpected behaviour:
`ln -s /run/secrets/etc/nginx/conf.d /etc/nginx`

It it were the case then I would modify the code.
But you need to report a reproducible issue.

**Comment by alejandro-colomar** [comment]
If `/etc/nginx/` happens to not exist (Maybe in the future you decide to remove not `/etc/nginx/conf.d/`, but the whole `/etc/nginx/`, or some other plausible cause) at the moment of `ln`, the behaviour will be unexpected.

**Comment by alejandro-colomar** [comment]
There's no need to be obscure.  This is the most important reason.

**Comment by scolomar** [comment]
> If `/etc/nginx/` happens to not exist (Maybe in the future you decide to remove not `/etc/nginx/conf.d/`, but the whole `/etc/nginx/`, or some other plausible cause), at the moment of `ln`, the behaviour will be unexpected.

You have to prove it. AFAIK it will not be the case. But if you can prove it then I will be happy to fix it.
It is very easy now with containers to check your hypothesis. I will not do it for you though.

**Comment by alejandro-colomar** [comment]
Try this on any computer:
```
rm -rf /etc/nginx
ln -s foo /etc/nginx
```

**Comment by scolomar** [comment]
> There's no need to be obscure. This is the most important reason.

I do not find it obscure. Maybe it is not explicit but I find it obvious. It would be a different thing if you can prove that it could be wrong under certain conditions.

**Comment by alejandro-colomar** [comment]
> Try this on any computer:
> 
> ```
> rm -rf /etc/nginx
> ln -s foo /etc/nginx
> ```

I guess you would expect to have `/etc/nginx/foo` as a link, but the link will be `/etc/nginx` itself

**Comment by scolomar** [comment]
> Try this on any computer:
> 
> ```
> rm -rf /etc/nginx
> ln -s foo /etc/nginx
> ```

Please try it yourself and report your results. But use the original full command under inspection:
`ln -s /run/secrets/etc/nginx/conf.d /etc/nginx`

If you are right then it will be terribly easy to prove it.

**Comment by alejandro-colomar** [comment]
![image](https://user-images.githubusercontent.com/21089465/84166503-442e4500-aa75-11ea-930c-8534f3a6349e.png)

**Comment by alejandro-colomar** [comment]
The target is irrelevant:

![image](https://user-images.githubusercontent.com/21089465/84166772-a6874580-aa75-11ea-839d-d75e3fb94945.png)

**Comment by scolomar** [comment]
So you propose to use `ln -s /run/secrets/etc/nginx/conf.d /etc/nginx/` instead.
Could you please try this command and check whether the result is better?

**Comment by alejandro-colomar** [comment]
That is one option.  The other is using -T and a link name explicitly, which is more explicit.

**Comment by alejandro-colomar** [comment]
Any of them work:

![image](https://user-images.githubusercontent.com/21089465/84168883-3af2a780-aa78-11ea-84db-2e5427e12f7a.png)

**Comment by scolomar** [comment]
Please propose a PR and I will check.

**Comment by alejandro-colomar** [comment]
Commit be746d6  fixes that

You can cherry-pick it from the PR #2

**Comment by scolomar** [comment]
The change is unnecessary given the FROM instruction.
