### ISSUE TITLE
Add aarch64 (arm64v8) image

### ISSUE THREAD

**Issue by alejandro-colomar** [secobau/nginx#10]

**Comment by scolomar** [comment]
There is no arm64v8 image available. But you can build your own.

**Comment by alejandro-colomar** [comment]
There is no dockerfile for it.

**Comment by scolomar** [comment]
Solved by https://github.com/secobau/nginx/releases/tag/v5.0-aarch64

**Comment by alejandro-colomar** [comment]
Debian uses the following convention:

[name_version-revision_arch.type](https://unix.stackexchange.com/a/190899)

You can use it and name your release v5.0_aarch64 instead of -aarch64

**Comment by scolomar** [comment]
https://github.com/secobau/nginx/releases/tag/v5.0_aarch64
